* Extracted models from RMOCSC.asc

* OPTO TRIAC
* Helmut Sennewald  8/10/2004
* MOC3021  I_trig=8mA
*  D+  D-  MT2  MT1
.SUBCKT MOC3021 1 2 3 4
.PARAM Itrig=8m
.PARAM RH1=20k
.PARAM RH2=20k
.PARAM RH3=16.7k
Q2 vb1 vb1p vd1 0 PNP1
Q1 vb1p vb1 4 0 NPN1
R3 vb1 4 {RH2}
D1 1 2 DL
R1 ctrl1 4 1
C1 ctrl1 4 10µ
R2 ctrl1 vb1 {RH1}
R4 vd1 vb1p {RH3}
B1 ctrl1 4 I=-500*I(D1)*3m/Itrig 
R6 vd2 vb2 {RH2}
D3 vd2 3 D1
Q3 vb2 vb2p 4 0 PNP1
Q4 vb2p vb2 vd2 0 NPN1
E1 vd2 N001 ctrl1 4 -1
R5 N001 vb2 {RH1}
R7 vb2p 4 {RH3}
D2 3 vd1 D1
R34 3 4 100MEG
.MODEL PNP1 PNP(Is=1e-15 BF=10 Cjc=10p Cje=20p Tf=0.1u Ise=1e-12)
.MODEL NPN1 NPN(Is=1e-15 BF=10 Cjc=10p Cje=20p Tf=0.1u Ise=1e-12)
.MODEL D1 D(Is=0.1u Rs=2 Cj0=50p)
.MODEL DL D(Is=1e-20 Rs=5)
.ENDS

.SUBCKT TIC106D    1  2             3
*       TERMINALS: A  G             K
Qpnp    6          4  1             Pfor      OFF
Qnpn    4          6  5             Nfor      OFF
Rfor    6          4  5G
Rrev    1          4  5G
Rshort  6          5  1MEG
Rlat    2          6  9.09
Ron     3          5  513.4m
Dfor    6          4  Zbrk
Drev    1          4  Zbrk
Dgate   6          5  Zgate
.MODEL  Zbrk       D  (IS=3.2E-16   IBV=100U  BV=400)
.MODEL  Zgate      D  (IS=1E-16     IBV=100U  BV=10      VJ=0.3)
.MODEL  Pfor       PNP(IS=5E-15     BF=6.10   CJE=5p     CJC=2p     TF=0.3U)
.MODEL  Nfor       NPN(IS=1E-12     ISE=1E-9  BF=10.0    RC=0.45    CJE=30p     CJC=2p      TF=0.3U)
.ENDS